"use client";

import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";

export type ConsciousnessStepId =
  | "start"
  | "destination"
  | "journey"
  | "experience"
  | "history"
  | "progress";

export const CONSCIOUSNESS_STEPS: ReadonlyArray<ConsciousnessStepId> = [
  "start",
  "destination",
  "journey",
  "experience",
  "history",
  "progress",
];

type ConsciousnessState = {
  /**
   * Current level (2–18, step 2). Stored after user selects it.
   * Null means not selected yet.
   */
  currentConsciousnessLevel: number | null;

  /**
   * Desired level (2–18, step 2). Stored after user selects it.
   * Null means not selected yet.
   */
  desiredConsciousnessLevel: number | null;

  /**
   * Optional user notes about why they want this shift.
   */
  contextNote: string;

  /**
   * Last generated journey id (UUID) returned from the analyze endpoint.
   * Useful for subsequent steps (journey/experience/history).
   */
  journeyId: string | null;

  /**
   * Suno prompt generated by Perplexity (stored client-side for convenience).
   */
  sunoPrompt: string | null;

  /**
   * Suno/n8n generation id (async job id).
   */
  sunoGenerationId: string | null;

  /**
   * Optional polling URL returned by the generate endpoint.
   */
  pollUrl: string | null;

  /**
   * Estimated wait time (seconds) returned by generate endpoint.
   */
  estimatedWaitTime: number | null;

  /**
   * Current generation phase (for UI).
   */
  generationStatus:
    | "idle"
    | "analyzing"
    | "generating"
    | "ready"
    | "failed"
    | "error";

  /**
   * Number of polling attempts made in the current session.
   */
  pollingAttempts: number;

  /**
   * Most recent Perplexity prompt we sent (useful for UI transparency).
   */
  perplexityPrompt: string | null;

  /**
   * Most recent Perplexity analysis payload (best-effort).
   */
  analysis: Record<string, any> | null;

  /**
   * Highest step index the user has unlocked (0–5).
   * - 0 = only Start
   * - 1 = can access Destination
   * - ...
   */
  maxUnlockedStep: number;

  setCurrentConsciousnessLevel: (level: number | null) => void;
  setDesiredConsciousnessLevel: (level: number | null) => void;
  setContextNote: (note: string) => void;
  setGenerationState: (next: {
    journeyId?: string | null;
    sunoPrompt?: string | null;
    sunoGenerationId?: string | null;
    pollUrl?: string | null;
    estimatedWaitTime?: number | null;
    perplexityPrompt?: string | null;
    analysis?: Record<string, any> | null;
  }) => void;
  setGenerationStatus: (status: ConsciousnessState["generationStatus"]) => void;
  incrementPollingAttempts: () => void;
  clearJourney: () => void;
  unlockStep: (stepIndex: number) => void;
  reset: () => void;
};

const clampUnlocked = (n: number) =>
  Math.max(0, Math.min(CONSCIOUSNESS_STEPS.length - 1, Math.floor(n)));

export const useConsciousnessStore = create<ConsciousnessState>()(
  persist(
    (set, get) => ({
      currentConsciousnessLevel: null,
      desiredConsciousnessLevel: null,
      contextNote: "",
      journeyId: null,
      sunoPrompt: null,
      sunoGenerationId: null,
      pollUrl: null,
      estimatedWaitTime: null,
      generationStatus: "idle",
      pollingAttempts: 0,
      perplexityPrompt: null,
      analysis: null,
      maxUnlockedStep: 0,

      setCurrentConsciousnessLevel: (level) => {
        if (level === null) {
          set({ currentConsciousnessLevel: null });
          return;
        }

        const n = Math.floor(level);
        if (!Number.isFinite(n) || n < 2 || n > 18) return;

        // Enforce 2-step ladder values: 2,4,...,18
        const snapped = n % 2 === 0 ? n : n - 1;
        set({ currentConsciousnessLevel: snapped });
      },

      setDesiredConsciousnessLevel: (level) => {
        if (level === null) {
          set({ desiredConsciousnessLevel: null });
          return;
        }

        const n = Math.floor(level);
        if (!Number.isFinite(n) || n < 2 || n > 18) return;

        // Enforce 2-step ladder values: 2,4,...,18
        const snapped = n % 2 === 0 ? n : n - 1;
        set({ desiredConsciousnessLevel: snapped });
      },

      setContextNote: (note) => {
        set({ contextNote: String(note ?? "") });
      },

      setGenerationState: (next) => {
        set({
          journeyId: next.journeyId ?? get().journeyId,
          sunoPrompt: next.sunoPrompt ?? get().sunoPrompt,
          sunoGenerationId: next.sunoGenerationId ?? get().sunoGenerationId,
          pollUrl: next.pollUrl ?? get().pollUrl,
          estimatedWaitTime: next.estimatedWaitTime ?? get().estimatedWaitTime,
          perplexityPrompt: next.perplexityPrompt ?? get().perplexityPrompt,
          analysis: next.analysis ?? get().analysis,
        });
      },

      setGenerationStatus: (status) => set({ generationStatus: status }),

      incrementPollingAttempts: () =>
        set({ pollingAttempts: (get().pollingAttempts ?? 0) + 1 }),

      clearJourney: () =>
        set({
          journeyId: null,
          sunoPrompt: null,
          sunoGenerationId: null,
          pollUrl: null,
          estimatedWaitTime: null,
          generationStatus: "idle",
          pollingAttempts: 0,
          perplexityPrompt: null,
          analysis: null,
        }),

      unlockStep: (stepIndex) => {
        const next = clampUnlocked(stepIndex);
        set({ maxUnlockedStep: Math.max(get().maxUnlockedStep, next) });
      },

      reset: () =>
        set({
          currentConsciousnessLevel: null,
          desiredConsciousnessLevel: null,
          contextNote: "",
          journeyId: null,
          sunoPrompt: null,
          sunoGenerationId: null,
          pollUrl: null,
          estimatedWaitTime: null,
          generationStatus: "idle",
          pollingAttempts: 0,
          perplexityPrompt: null,
          analysis: null,
          maxUnlockedStep: 0,
        }),
    }),
    {
      name: "consciousness-portal",
      storage: createJSONStorage(() => localStorage),
      version: 1,
    }
  )
);

